[package]
name = "r-piece"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.4"
lazy_static = "1.4.0"
# phf = { version = "0.11.2", features = ["full"] }
thiserror = "1.0.61"
